name: Smokeview
on: push
jobs:
  build:
    name: Build Smokeview
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        lua: [true,false]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        shell: bash
        env:
          PLATFORM: ${{ matrix.os }}
          LUA: ${{ matrix.lua }}
        run: |
          if [[ "$PLATFORM" == "macos-latest" ]]; then
            brew install gcc
            brew reinstall gcc
            ls /usr/local/Cellar/gcc/10.2.0/lib/gcc/10/*
            cp /usr/local/Cellar/gcc/10.2.0/lib/gcc/10/libgfortran* Build/LIBS/gnu_osx_64
            pushd Build/smokeview/gnu_osx_64
            if [[ "$LUA" == true ]]; then
              ./make_smokeview_lua.sh
            else
              ./make_smokeview.sh
            fi
            popd
            cp Build/smokeview/gnu_osx_64/smokeview_osx_64 smokeview
          fi
          if [[ "$PLATFORM" == "ubuntu-latest" ]]; then
            sudo apt-get install build-essential gfortran freeglut3-dev libx11-dev libxmu-dev libxi-dev
            pushd Build/smokeview/gnu_linux_64
            if [[ "$LUA" == true ]]; then
              ./make_smokeview_lua.sh
            else
              ./make_smokeview.sh
            fi
            popd
            cp Build/smokeview/gnu_linux_64/smokeview_linux_64 smokeview
          fi
          if [[ "$PLATFORM" == "windows-latest" ]]; then
            choco install make
            pushd Build/smokeview/mingw_win_64
            if [[ "$LUA" == true ]]; then
              ./make_smokeview_lua.sh
            else
              ./make_smokeview.sh
            fi
            popd
            cp Build/smokeview/mingw_win_64/smokeview_mingw_64 smokeview
          fi
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: smokeview
          path: smokeview
